// Mock Data for BloodConnect Olongapo

export const mockDonors = [
  {
    id: 1,
    name: "Juan Dela Cruz",
    email: "juan.delacruz@email.com",
    bloodType: "O+",
    contact: "0917-123-4567",
    address: "Barangay Barretto",
    barangay: "Barretto",
    lastDonation: "2025-08-15",
    status: "active",
    emailAlerts: true,
  },
  {
    id: 2,
    name: "Maria Santos",
    email: "maria.santos@email.com",
    bloodType: "A+",
    contact: "0918-234-5678",
    address: "Barangay East Bajac-Bajac",
    barangay: "East Bajac-Bajac",
    lastDonation: "2025-07-20",
    status: "active",
    emailAlerts: true,
  },
  {
    id: 3,
    name: "Pedro Reyes",
    email: "pedro.reyes@email.com",
    bloodType: "B+",
    contact: "0919-345-6789",
    address: "Barangay West Bajac-Bajac",
    barangay: "West Bajac-Bajac",
    lastDonation: "2025-06-10",
    status: "active",
    emailAlerts: false,
  },
  {
    id: 4,
    name: "Ana Garcia",
    email: "ana.garcia@email.com",
    bloodType: "AB+",
    contact: "0920-456-7890",
    address: "Barangay Gordon Heights",
    barangay: "Gordon Heights",
    lastDonation: "2025-09-01",
    status: "active",
    emailAlerts: true,
  },
  {
    id: 5,
    name: "Carlos Mendoza",
    email: "carlos.mendoza@email.com",
    bloodType: "O-",
    contact: "0921-567-8901",
    address: "Barangay New Ilalim",
    barangay: "New Ilalim",
    lastDonation: "2025-05-15",
    status: "active",
    emailAlerts: true,
  },
  {
    id: 6,
    name: "Rosa Fernandez",
    email: "rosa.fernandez@email.com",
    bloodType: "A-",
    contact: "0922-678-9012",
    address: "Barangay Pag-asa",
    barangay: "Pag-asa",
    lastDonation: "2025-08-25",
    status: "active",
    emailAlerts: true,
  },
  {
    id: 7,
    name: "Miguel Torres",
    email: "miguel.torres@email.com",
    bloodType: "B-",
    contact: "0923-789-0123",
    address: "Barangay Santa Rita",
    barangay: "Santa Rita",
    lastDonation: "2025-07-05",
    status: "active",
    emailAlerts: false,
  },
  {
    id: 8,
    name: "Elena Cruz",
    email: "elena.cruz@email.com",
    bloodType: "AB-",
    contact: "0924-890-1234",
    address: "Barangay Asinan",
    barangay: "Asinan",
    lastDonation: "2025-06-20",
    status: "active",
    emailAlerts: true,
  },
];

export const mockRequests = [
  {
    id: 1,
    hospitalName: "James L. Gordon Memorial Hospital",
    bloodType: "O+",
    quantity: 3,
    urgency: "urgent",
    notes: "Emergency surgery patient",
    status: "active",
    createdAt: "2025-10-14T08:30:00",
    matchedDonors: 5,
  },
  {
    id: 2,
    hospitalName: "Olongapo City General Hospital",
    bloodType: "A+",
    quantity: 2,
    urgency: "normal",
    notes: "Scheduled transfusion",
    status: "active",
    createdAt: "2025-10-13T14:15:00",
    matchedDonors: 3,
  },
  {
    id: 3,
    hospitalName: "St. James Hospital",
    bloodType: "B+",
    quantity: 1,
    urgency: "urgent",
    notes: "Accident victim",
    status: "fulfilled",
    createdAt: "2025-10-12T10:00:00",
    matchedDonors: 2,
  },
];

export const mockAlerts = [
  {
    id: 1,
    title: "Urgent: O+ Blood Needed",
    message: "James L. Gordon Memorial Hospital needs 3 units of O+ blood for emergency surgery.",
    hospitalName: "James L. Gordon Memorial Hospital",
    bloodType: "O+",
    quantity: 3,
    sentAt: "2025-10-14T08:35:00",
    status: "sent",
  },
  {
    id: 2,
    title: "Blood Request: A+ Blood",
    message: "Olongapo City General Hospital needs 2 units of A+ blood for scheduled transfusion.",
    hospitalName: "Olongapo City General Hospital",
    bloodType: "A+",
    quantity: 2,
    sentAt: "2025-10-13T14:20:00",
    status: "sent",
  },
  {
    id: 3,
    title: "Emergency: B+ Blood Required",
    message: "St. James Hospital urgently needs 1 unit of B+ blood for accident victim.",
    hospitalName: "St. James Hospital",
    bloodType: "B+",
    quantity: 1,
    sentAt: "2025-10-12T10:05:00",
    status: "fulfilled",
  },
];

export const mockAnalytics = {
  totalDonors: 8,
  activeRequests: 2,
  totalRequests: 3,
  donorsByBloodType: {
    "O+": 1,
    "O-": 1,
    "A+": 1,
    "A-": 1,
    "B+": 1,
    "B-": 1,
    "AB+": 1,
    "AB-": 1,
  },
  donorsByBarangay: {
    "Barretto": 1,
    "East Bajac-Bajac": 1,
    "West Bajac-Bajac": 1,
    "Gordon Heights": 1,
    "New Ilalim": 1,
    "Pag-asa": 1,
    "Santa Rita": 1,
    "Asinan": 1,
  },
  recentActivity: [
    { date: "2025-10-14", event: "Blood request created", count: 1 },
    { date: "2025-10-13", event: "Blood request created", count: 1 },
    { date: "2025-10-12", event: "Blood request fulfilled", count: 1 },
  ],
};

export const bloodTypes = ["O+", "O-", "A+", "A-", "B+", "B-", "AB+", "AB-"];

export const barangays = [
  "Asinan",
  "Barretto",
  "East Bajac-Bajac",
  "East Tapinac",
  "Gordon Heights",
  "Kalaklan",
  "Mabayuan",
  "New Ilalim",
  "New Kababae",
  "New Kalalake",
  "New Cabalan",
  "Old Cabalan",
  "Pag-asa",
  "Santa Rita",
  "West Bajac-Bajac",
  "West Tapinac",
];

export const hospitals = [
  "James L. Gordon Memorial Hospital",
  "Olongapo City General Hospital",
  "St. James Hospital",
  "Adventist Medical Center Olongapo",
];
